/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-03-04 20:48:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.User;
import java.util.List;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("            ");
 // Prevent caching response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate" );
                response.setHeader("Pragma", "no-cache" ); response.setDateHeader("Expires", 0); User user=(User)
                session.getAttribute("user"); if (user==null || !"admin".equals(user.getRole())) {
                response.sendRedirect("login.jsp"); return; } 
      out.write("\r\n");
      out.write("                <!DOCTYPE html>\r\n");
      out.write("                <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("                <head>\r\n");
      out.write("                    <meta charset=\"UTF-8\">\r\n");
      out.write("                    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                    <title>Admin Dashboard - Smart Attendance</title>\r\n");
      out.write("                    <!-- Bootstrap CSS -->\r\n");
      out.write("                    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("                        rel=\"stylesheet\">\r\n");
      out.write("                    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\"\r\n");
      out.write("                        rel=\"stylesheet\">\r\n");
      out.write("                    <!-- FontAwesome -->\r\n");
      out.write("                    <link rel=\"stylesheet\"\r\n");
      out.write("                        href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("                    <style>\r\n");
      out.write("                        body {\r\n");
      out.write("                            font-family: 'Inter', sans-serif;\r\n");
      out.write("                            background-color: #f4f6f9;\r\n");
      out.write("                            overflow-x: hidden;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        .wrapper {\r\n");
      out.write("                            display: flex;\r\n");
      out.write("                            width: 100%;\r\n");
      out.write("                            align-items: stretch;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        /* Sidebar styling */\r\n");
      out.write("                        #sidebar {\r\n");
      out.write("                            min-width: 250px;\r\n");
      out.write("                            max-width: 250px;\r\n");
      out.write("                            background: #2c3e50;\r\n");
      out.write("                            color: #fff;\r\n");
      out.write("                            transition: all 0.3s;\r\n");
      out.write("                            min-height: 100vh;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        #sidebar .sidebar-header {\r\n");
      out.write("                            padding: 20px;\r\n");
      out.write("                            background: #1a252f;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        #sidebar ul.components {\r\n");
      out.write("                            padding: 20px 0;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        #sidebar ul p {\r\n");
      out.write("                            color: #fff;\r\n");
      out.write("                            padding: 10px;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        #sidebar ul li a {\r\n");
      out.write("                            padding: 10px 20px;\r\n");
      out.write("                            font-size: 1.1em;\r\n");
      out.write("                            display: block;\r\n");
      out.write("                            color: #ecf0f1;\r\n");
      out.write("                            text-decoration: none;\r\n");
      out.write("                            transition: 0.3s;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        #sidebar ul li a:hover,\r\n");
      out.write("                        #sidebar ul li.active>a {\r\n");
      out.write("                            color: #3498db;\r\n");
      out.write("                            background: #fff;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        #sidebar ul li a i {\r\n");
      out.write("                            margin-right: 10px;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        /* Content styling */\r\n");
      out.write("                        #content {\r\n");
      out.write("                            width: 100%;\r\n");
      out.write("                            padding: 20px;\r\n");
      out.write("                            min-height: 100vh;\r\n");
      out.write("                            transition: all 0.3s;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        .top-navbar {\r\n");
      out.write("                            background: #fff;\r\n");
      out.write("                            padding: 15px 20px;\r\n");
      out.write("                            border-radius: 10px;\r\n");
      out.write("                            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05);\r\n");
      out.write("                            margin-bottom: 20px;\r\n");
      out.write("                            display: flex;\r\n");
      out.write("                            justify-content: space-between;\r\n");
      out.write("                            align-items: center;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        .card-custom {\r\n");
      out.write("                            border: none;\r\n");
      out.write("                            border-radius: 15px;\r\n");
      out.write("                            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);\r\n");
      out.write("                            margin-bottom: 20px;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        .card-header-custom {\r\n");
      out.write("                            background-color: #fff;\r\n");
      out.write("                            border-bottom: 1px solid #f0f0f0;\r\n");
      out.write("                            padding: 15px 20px;\r\n");
      out.write("                            border-top-left-radius: 15px;\r\n");
      out.write("                            border-top-right-radius: 15px;\r\n");
      out.write("                            font-weight: 600;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        .table> :not(caption)>*>* {\r\n");
      out.write("                            padding: 1rem 1rem;\r\n");
      out.write("                        }\r\n");
      out.write("                    </style>\r\n");
      out.write("                </head>\r\n");
      out.write("\r\n");
      out.write("                <body>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"wrapper\">\r\n");
      out.write("                        <!-- Sidebar -->\r\n");
      out.write("                        <nav id=\"sidebar\">\r\n");
      out.write("                            <div class=\"sidebar-header\">\r\n");
      out.write("                                <h3><i class=\"fa-solid fa-graduation-cap\"></i> Admin Panel</h3>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <ul class=\"list-unstyled components\">\r\n");
      out.write("                                <li class=\"active\">\r\n");
      out.write("                                    <a href=\"AdminServlet\"><i class=\"fa-solid fa-users\"></i> Users</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa-solid fa-book\"></i> Courses & Enrollments</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa-solid fa-calendar-check\"></i> Attendance</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Page Content -->\r\n");
      out.write("                        <div id=\"content\">\r\n");
      out.write("                            <div class=\"top-navbar\">\r\n");
      out.write("                                <h4 class=\"mb-0\">Dashboard</h4>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <span class=\"me-3 fw-bold\"><i class=\"fa-solid fa-user-shield text-primary\"></i>\r\n");
      out.write("                                        ");
      out.print( user.getName() );
      out.write("\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <a href=\"LoginServlet?action=logout\"\r\n");
      out.write("                                        class=\"btn btn-sm btn-outline-danger\">Logout</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            ");
 if (request.getParameter("success") !=null) { 
      out.write("\r\n");
      out.write("                                <div class=\"alert alert-success alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("                                    ");
      out.print( request.getParameter("success") );
      out.write("\r\n");
      out.write("                                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                                    ");
 if (request.getParameter("error") !=null) { 
      out.write("\r\n");
      out.write("                                        <div class=\"alert alert-danger alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("                                            ");
      out.print( request.getParameter("error") );
      out.write("\r\n");
      out.write("                                                <button type=\"button\" class=\"btn-close\"\r\n");
      out.write("                                                    data-bs-dismiss=\"alert\"></button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <!-- Manage Users Table -->\r\n");
      out.write("                                                <div class=\"col-lg-8\">\r\n");
      out.write("                                                    <div class=\"card card-custom\">\r\n");
      out.write("                                                        <div\r\n");
      out.write("                                                            class=\"card-header-custom d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                                            <span>All Registered Users</span>\r\n");
      out.write("                                                            <span class=\"badge bg-primary rounded-pill\">Total:\r\n");
      out.write("                                                                ");
 List<User> usersList = (List<User>)
                                                                        request.getAttribute("users");
                                                                        out.print(usersList != null ? usersList.size() :
                                                                        "0");
                                                                        
      out.write("\r\n");
      out.write("                                                            </span>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"card-body p-0\">\r\n");
      out.write("                                                            <div class=\"table-responsive\">\r\n");
      out.write("                                                                <table class=\"table table-hover mb-0\">\r\n");
      out.write("                                                                    <thead class=\"table-light\">\r\n");
      out.write("                                                                        <tr>\r\n");
      out.write("                                                                            <th>ID</th>\r\n");
      out.write("                                                                            <th>Name</th>\r\n");
      out.write("                                                                            <th>Email</th>\r\n");
      out.write("                                                                            <th>Role</th>\r\n");
      out.write("                                                                            <th>Joined Date</th>\r\n");
      out.write("                                                                        </tr>\r\n");
      out.write("                                                                    </thead>\r\n");
      out.write("                                                                    <tbody>\r\n");
      out.write("                                                                        ");
 if (usersList !=null && !usersList.isEmpty())
                                                                            { for (User u : usersList) { 
      out.write("\r\n");
      out.write("                                                                            <tr>\r\n");
      out.write("                                                                                <td>#");
      out.print( u.getId() );
      out.write("\r\n");
      out.write("                                                                                </td>\r\n");
      out.write("                                                                                <td class=\"fw-bold\">\r\n");
      out.write("                                                                                    ");
      out.print( u.getName() );
      out.write("\r\n");
      out.write("                                                                                </td>\r\n");
      out.write("                                                                                <td>\r\n");
      out.write("                                                                                    ");
      out.print( u.getEmail() );
      out.write("\r\n");
      out.write("                                                                                </td>\r\n");
      out.write("                                                                                <td>\r\n");
      out.write("                                                                                    ");
 if ("admin".equals(u.getRole()))
                                                                                        { 
      out.write("\r\n");
      out.write("                                                                                        <span\r\n");
      out.write("                                                                                            class=\"badge bg-danger\">Admin</span>\r\n");
      out.write("                                                                                        ");
 } else { 
      out.write("\r\n");
      out.write("                                                                                            <span\r\n");
      out.write("                                                                                                class=\"badge bg-success\">Student</span>\r\n");
      out.write("                                                                                            ");
 } 
      out.write("\r\n");
      out.write("                                                                                </td>\r\n");
      out.write("                                                                                <td class=\"text-muted\">\r\n");
      out.write("                                                                                    ");
      out.print( u.getCreatedAt() );
      out.write("\r\n");
      out.write("                                                                                </td>\r\n");
      out.write("                                                                            </tr>\r\n");
      out.write("                                                                            ");
 } } else { 
      out.write("\r\n");
      out.write("                                                                                <tr>\r\n");
      out.write("                                                                                    <td colspan=\"5\"\r\n");
      out.write("                                                                                        class=\"text-center py-4\">No\r\n");
      out.write("                                                                                        users found in database.</td>\r\n");
      out.write("                                                                                </tr>\r\n");
      out.write("                                                                                ");
 } 
      out.write("\r\n");
      out.write("                                                                    </tbody>\r\n");
      out.write("                                                                </table>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Add Admin Form -->\r\n");
      out.write("                                                <div class=\"col-lg-4\">\r\n");
      out.write("                                                    <div class=\"card card-custom\">\r\n");
      out.write("                                                        <div class=\"card-header-custom\">\r\n");
      out.write("                                                            Add New Admin\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"card-body\">\r\n");
      out.write("                                                            <form action=\"");
      out.print(request.getContextPath());
      out.write("/AdminServlet\"\r\n");
      out.write("                                                                method=\"POST\">\r\n");
      out.write("                                                                <input type=\"hidden\" name=\"action\" value=\"addAdmin\">\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"mb-3\">\r\n");
      out.write("                                                                    <label\r\n");
      out.write("                                                                        class=\"form-label text-muted small fw-bold\">Full\r\n");
      out.write("                                                                        Name</label>\r\n");
      out.write("                                                                    <input type=\"text\" class=\"form-control\" name=\"name\"\r\n");
      out.write("                                                                        required>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"mb-3\">\r\n");
      out.write("                                                                    <label\r\n");
      out.write("                                                                        class=\"form-label text-muted small fw-bold\">Email\r\n");
      out.write("                                                                        Address</label>\r\n");
      out.write("                                                                    <input type=\"email\" class=\"form-control\"\r\n");
      out.write("                                                                        name=\"email\" required>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"mb-3\">\r\n");
      out.write("                                                                    <label\r\n");
      out.write("                                                                        class=\"form-label text-muted small fw-bold\">Password</label>\r\n");
      out.write("                                                                    <input type=\"password\" class=\"form-control\"\r\n");
      out.write("                                                                        name=\"password\" required>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <button type=\"submit\"\r\n");
      out.write("                                                                    class=\"btn btn-primary w-100\">Create Admin\r\n");
      out.write("                                                                    Account</button>\r\n");
      out.write("                                                            </form>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("                </body>\r\n");
      out.write("\r\n");
      out.write("                </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
