/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-03-04 20:46:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Login - Smart Attendance</title>\r\n");
      out.write("        <!-- Bootstrap CSS -->\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        <style>\r\n");
      out.write("            body {\r\n");
      out.write("                font-family: 'Inter', sans-serif;\r\n");
      out.write("                background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);\r\n");
      out.write("                height: 100vh;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-container {\r\n");
      out.write("                background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("                padding: 3rem;\r\n");
      out.write("                border-radius: 15px;\r\n");
      out.write("                box-shadow: 0 15px 35px rgba(0, 0, 0, 0.1);\r\n");
      out.write("                max-width: 400px;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-title {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin-bottom: 2rem;\r\n");
      out.write("                color: #2c3e50;\r\n");
      out.write("                font-weight: 700;\r\n");
      out.write("                font-size: 2rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-control {\r\n");
      out.write("                border-radius: 10px;\r\n");
      out.write("                padding: 12px 15px;\r\n");
      out.write("                margin-bottom: 1.5rem;\r\n");
      out.write("                border: 1px solid #ddd;\r\n");
      out.write("                transition: all 0.3s;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-control:focus {\r\n");
      out.write("                box-shadow: 0 0 10px rgba(52, 152, 219, 0.2);\r\n");
      out.write("                border-color: #3498db;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-login {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                padding: 12px;\r\n");
      out.write("                background-color: #3498db;\r\n");
      out.write("                border: none;\r\n");
      out.write("                color: white;\r\n");
      out.write("                font-weight: 600;\r\n");
      out.write("                border-radius: 10px;\r\n");
      out.write("                font-size: 1.1rem;\r\n");
      out.write("                transition: background-color 0.3s;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-login:hover {\r\n");
      out.write("                background-color: #2980b9;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .signup-link {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin-top: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .signup-link a {\r\n");
      out.write("                color: #2ecc71;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                font-weight: 600;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .alert-success-custom {\r\n");
      out.write("                background-color: #d4edda;\r\n");
      out.write("                color: #155724;\r\n");
      out.write("                border-radius: 10px;\r\n");
      out.write("                padding: 10px;\r\n");
      out.write("                margin-bottom: 1.5rem;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container d-flex justify-content-center\">\r\n");
      out.write("            <div class=\"login-container\">\r\n");
      out.write("                <h2 class=\"login-title\">Welcome Back</h2>\r\n");
      out.write("\r\n");
      out.write("                ");
 if (request.getParameter("success") !=null) { 
      out.write("\r\n");
      out.write("                    <div class=\"alert-success-custom\">\r\n");
      out.write("                        ");
      out.print( request.getParameter("success") );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        ");
 if (request.getParameter("error") !=null) { 
      out.write("\r\n");
      out.write("                            <div class=\"alert alert-danger\" role=\"alert\"\r\n");
      out.write("                                style=\"border-radius:10px; text-align:center; padding:10px; margin-bottom:1.5rem;\">\r\n");
      out.write("                                ");
      out.print( request.getParameter("error") );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <form action=\"");
      out.print(request.getContextPath());
      out.write("/LoginServlet\" method=\"POST\">\r\n");
      out.write("                                    <div class=\"mb-3\">\r\n");
      out.write("                                        <input type=\"email\" class=\"form-control\" name=\"email\"\r\n");
      out.write("                                            placeholder=\"Email Address\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"mb-3\">\r\n");
      out.write("                                        <input type=\"password\" class=\"form-control\" name=\"password\"\r\n");
      out.write("                                            placeholder=\"Password\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-login\">Login</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"signup-link\">\r\n");
      out.write("                                    Don't have an account? <a href=\"signup.jsp\">Sign up here</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
