/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-03-04 20:47:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.User;
import model.Course;
import java.util.List;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("model.Course");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("                ");
 // Prevent caching to guarantee redirect on back button after logout
                    response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate" );
                    response.setHeader("Pragma", "no-cache" ); response.setDateHeader("Expires", 0); User user=(User)
                    session.getAttribute("user"); if (user==null || !"student".equals(user.getRole())) {
                    response.sendRedirect("login.jsp"); return; } 
      out.write("\r\n");
      out.write("                    <!DOCTYPE html>\r\n");
      out.write("                    <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("                    <head>\r\n");
      out.write("                        <meta charset=\"UTF-8\">\r\n");
      out.write("                        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                        <title>Student Profile - Smart Attendance</title>\r\n");
      out.write("                        <!-- Bootstrap CSS -->\r\n");
      out.write("                        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("                            rel=\"stylesheet\">\r\n");
      out.write("                        <link\r\n");
      out.write("                            href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\"\r\n");
      out.write("                            rel=\"stylesheet\">\r\n");
      out.write("                        <style>\r\n");
      out.write("                            body {\r\n");
      out.write("                                font-family: 'Inter', sans-serif;\r\n");
      out.write("                                background-color: #f8f9fa;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .navbar-custom {\r\n");
      out.write("                                background-color: #2c3e50;\r\n");
      out.write("                                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .navbar-custom .navbar-brand,\r\n");
      out.write("                            .navbar-custom .nav-link {\r\n");
      out.write("                                color: #fff;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .profile-header {\r\n");
      out.write("                                background: linear-gradient(135deg, #3498db, #8e44ad);\r\n");
      out.write("                                color: white;\r\n");
      out.write("                                padding: 3rem 0;\r\n");
      out.write("                                margin-bottom: 2rem;\r\n");
      out.write("                                border-bottom-left-radius: 20px;\r\n");
      out.write("                                border-bottom-right-radius: 20px;\r\n");
      out.write("                                box-shadow: 0 10px 20px rgba(0, 0, 0, 0.05);\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .card-custom {\r\n");
      out.write("                                border: none;\r\n");
      out.write("                                border-radius: 15px;\r\n");
      out.write("                                box-shadow: 0 5px 15px rgba(0, 0, 0, 0.05);\r\n");
      out.write("                                transition: transform 0.2s;\r\n");
      out.write("                                margin-bottom: 1.5rem;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .card-custom:hover {\r\n");
      out.write("                                transform: translateY(-5px);\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .card-title {\r\n");
      out.write("                                font-weight: 600;\r\n");
      out.write("                                color: #2c3e50;\r\n");
      out.write("                                border-bottom: 2px solid #f1f2f6;\r\n");
      out.write("                                padding-bottom: 10px;\r\n");
      out.write("                                margin-bottom: 15px;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .btn-enroll {\r\n");
      out.write("                                background-color: #2ecc71;\r\n");
      out.write("                                color: white;\r\n");
      out.write("                                border-radius: 20px;\r\n");
      out.write("                                padding: 8px 20px;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .btn-enroll:hover {\r\n");
      out.write("                                background-color: #27ae60;\r\n");
      out.write("                                color: white;\r\n");
      out.write("                            }\r\n");
      out.write("                        </style>\r\n");
      out.write("                    </head>\r\n");
      out.write("\r\n");
      out.write("                    <body>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Navigation -->\r\n");
      out.write("                        <nav class=\"navbar navbar-expand-lg navbar-custom\">\r\n");
      out.write("                            <div class=\"container\">\r\n");
      out.write("                                <a class=\"navbar-brand fw-bold\" href=\"#\">Smart Attendance</a>\r\n");
      out.write("                                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                                    data-bs-target=\"#navbarNav\">\r\n");
      out.write("                                    <span class=\"navbar-toggler-icon\" style=\"filter: invert(1);\"></span>\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <div class=\"collapse navbar-collapse justify-content-end\" id=\"navbarNav\">\r\n");
      out.write("                                    <ul class=\"navbar-nav\">\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link\" href=\"#\">Profile</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link text-danger\" href=\"LoginServlet?action=logout\">Logout</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </nav>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Profile Header -->\r\n");
      out.write("                        <div class=\"profile-header text-center\">\r\n");
      out.write("                            <div class=\"container\">\r\n");
      out.write("                                <h1 class=\"display-4 fw-bold\">Welcome, ");
      out.print( user.getName() );
      out.write("!</h1>\r\n");
      out.write("                                <p class=\"lead mb-0\">\r\n");
      out.write("                                    ");
      out.print( user.getEmail() );
      out.write("\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Main Content -->\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("                            ");
 if (request.getParameter("success") !=null) { 
      out.write("\r\n");
      out.write("                                <div class=\"alert alert-success alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("                                    ");
      out.print( request.getParameter("success") );
      out.write("\r\n");
      out.write("                                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                                    ");
 if (request.getParameter("error") !=null) { 
      out.write("\r\n");
      out.write("                                        <div class=\"alert alert-danger alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("                                            ");
      out.print( request.getParameter("error") );
      out.write("\r\n");
      out.write("                                                <button type=\"button\" class=\"btn-close\"\r\n");
      out.write("                                                    data-bs-dismiss=\"alert\"></button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <!-- Left Column: Courses to Enroll -->\r\n");
      out.write("                                                <div class=\"col-md-6\">\r\n");
      out.write("                                                    <div class=\"card card-custom p-4\">\r\n");
      out.write("                                                        <h4 class=\"card-title\">Available Courses</h4>\r\n");
      out.write("\r\n");
      out.write("                                                        <form action=\"");
      out.print(request.getContextPath());
      out.write("/CourseServlet\"\r\n");
      out.write("                                                            method=\"POST\">\r\n");
      out.write("                                                            <div class=\"mb-3\">\r\n");
      out.write("                                                                <label for=\"courseSelect\"\r\n");
      out.write("                                                                    class=\"form-label text-muted\">Select a course to\r\n");
      out.write("                                                                    enroll:</label>\r\n");
      out.write("                                                                <select class=\"form-select\" id=\"courseSelect\"\r\n");
      out.write("                                                                    name=\"courseId\" required>\r\n");
      out.write("                                                                    <option value=\"\" disabled selected>-- Choose Course\r\n");
      out.write("                                                                        --</option>\r\n");
      out.write("                                                                    ");
 List<Course> allCourses = (List<Course>)
                                                                            request.getAttribute("allCourses");
                                                                            if(allCourses != null &&
                                                                            !allCourses.isEmpty()) {
                                                                            for(Course c : allCourses) {
                                                                            
      out.write("\r\n");
      out.write("                                                                            <option value=\"");
      out.print( c.getCourseId() );
      out.write("\">\r\n");
      out.write("                                                                                ");
      out.print( c.getCourseCode() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(
                                                                                        c.getCourseName() );
      out.write("\r\n");
      out.write("                                                                            </option>\r\n");
      out.write("                                                                            ");
 } } else { 
      out.write("\r\n");
      out.write("                                                                                <option value=\"\" disabled>No courses\r\n");
      out.write("                                                                                    available</option>\r\n");
      out.write("                                                                                ");
 } 
      out.write("\r\n");
      out.write("                                                                </select>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <button type=\"submit\" class=\"btn btn-enroll w-100\">Enroll\r\n");
      out.write("                                                                Course</button>\r\n");
      out.write("                                                        </form>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Right Column: Enrolled Courses -->\r\n");
      out.write("                                                <div class=\"col-md-6\">\r\n");
      out.write("                                                    <div class=\"card card-custom p-4\">\r\n");
      out.write("                                                        <h4 class=\"card-title\">My Enrolled Courses</h4>\r\n");
      out.write("                                                        <ul class=\"list-group list-group-flush mt-2\">\r\n");
      out.write("                                                            ");
 List<Course> enrolledCourses = (List<Course>)
                                                                    request.getAttribute("enrolledCourses");
                                                                    if(enrolledCourses != null &&
                                                                    !enrolledCourses.isEmpty()) {
                                                                    for(Course c : enrolledCourses) {
                                                                    
      out.write("\r\n");
      out.write("                                                                    <li\r\n");
      out.write("                                                                        class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                                                        <div>\r\n");
      out.write("                                                                            <h6 class=\"mb-0 fw-bold\">\r\n");
      out.write("                                                                                ");
      out.print( c.getCourseName() );
      out.write("\r\n");
      out.write("                                                                            </h6>\r\n");
      out.write("                                                                            <small class=\"text-muted\">\r\n");
      out.write("                                                                                ");
      out.print( c.getCourseCode() );
      out.write("\r\n");
      out.write("                                                                            </small>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <span\r\n");
      out.write("                                                                            class=\"badge bg-primary rounded-pill\">Enrolled</span>\r\n");
      out.write("                                                                    </li>\r\n");
      out.write("                                                                    ");
 } } else { 
      out.write("\r\n");
      out.write("                                                                        <li class=\"list-group-item text-muted\">You are\r\n");
      out.write("                                                                            not enrolled in any courses yet.</li>\r\n");
      out.write("                                                                        ");
 } 
      out.write("\r\n");
      out.write("                                                        </ul>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <script\r\n");
      out.write("                            src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("                    </body>\r\n");
      out.write("\r\n");
      out.write("                    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
